spring:
  datasource:
    url: jdbc:h2:mem:MyWebDatabase;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize=true:
  h2:
    console:
      enabled: true
      path: /console
  mvc:
    view:
      prefix: /webPages/
      suffix: .jsp